version: '3.7'

services:
  neo4j:
    image: neo4j
    env_file:
      - .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data
      - ./src/db/:/cypher-scripts

  app:
    build: .
    depends_on:
      - neo4j
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
